server:
  port: 6543
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://124.223.213.54:3306/mybatis?useUnicode=true&useSSL=false
    username: root
    password: 8uhb$RFV

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  # 打印sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl